### PR TITLE
reduce file size with better codec and palette adjustment

### PR DESCRIPTION
**Pull request by lpmi-13**
by using the OxiPNG codec from the fantastic site, https://squoosh.app/, along with reducing the palette to 100 colors, we're able to get a 70% reduction in file size without any discernible loss in image quality.

### CODE REVIEW

**Comment by lpmi-13** [comment]
noticed this while on https://raft.github.io/, since that image alone accounts for a little under half of the entire network footprint for the page, and reducing the size would speed the page up considerably.

big image transfer

**Comment by ongardie** [comment]
Ah, that's cool. Do you mind re-encoding `annie-sticker.png` too? Seems like we might as well keep them symmetric, even if we don't have the same motivation for `annie-sticker.png`. And please add a quick note to the README that these were re-encoded with that codec.

Also or alternatively, should we just use an SVG on the website? See PR #2. It's 44KB and vector, so I think preferable? I'm sure I could get it smaller by clicking around in Inkscape, but that seemed small enough.

**Comment by lpmi-13** [comment]
yeah, I think we might as well go ahead and reduce the file size for the two PNGs and keep those (just since some older browsers still work better with them), and switch over to using SVGs for the site.

I went ahead and tweaked `annie-sticker.png` down to only 16 colors, and it still looks exactly the same to me (a slight bit more pixelated at extreme zoom). Screenshot below, so lemme know what you think and I can update this PR with that image and update the README as well.

color palette at 16

**Comment by ongardie** [comment]
Looks good to me @lpmi-13, thanks

**Comment by lpmi-13** [comment]
have added the optimized `annie-sticker.png` image...though was that the sort of wording you were requesting for the README? Can update it, no problem, just not sure what would be the most helpful to add.

**Comment by ongardie** [comment]
That's great @lpmi-13, thanks!

**Pull request merged**
